"""create runs table

Revision ID: e4170ff521ea
Revises: 
Create Date: 2026-06-01 19:51:09.781136
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e4170ff521ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('input', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'cancelled', name='run_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('runs')
    # drop_table does NOT drop the PG ENUM type; do it explicitly so a
    # later re-upgrade doesn't fail with "type run_status already exists".
    sa.Enum(name='run_status').drop(op.get_bind(), checkfirst=True)
